### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by TI0946** [TI0946/chat-space#17]
IPアドレス
3.114.181.237

**Comment by TI0946** [comment]
https://gyazo.com/505e76a38e049de46cb09d85dc4120da
一応フロントが崩れていることがよくあるようなので、gyazoも置いておきます。

**Comment by miyu-yamamoto** [comment]
石川さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ Sign upなどがボタンで表示されない**
https://gyazo.com/aafd261d06e28faa96fc3cd321e468da
**○ グループを作成したメンバーが削除できてしまう**
https://gyazo.com/d804260b39c08ee1a007daf812787342

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by TI0946** [comment]
直しました。

**Comment by naru6117** [comment]
石川さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の点はしっかり修正ができていました。
>○ グループを作成したメンバーが削除できてしまう

以下の点は修正が確認できませんでしたので、改めて修正をお願いします！
※本番環境へ反映されていない場合が多いので、そのあたり確認お願い致します。

[修正箇所]
>○ Sign upなどがボタンで表示されない

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by TI0946** [comment]
すみません。本番に反映させてなかったです。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
アカウント編集ページは「ボタン」表示ができていましたが、
**サインイン、サインアップ（新規登録）はボタン表示されていませんでした。**

カリキュラムの中にある、模範のchatspaceを参考に、修正をお願いします。
https://chat-space-sample.herokuapp.com/

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by TI0946** [comment]
ローカルの方ではいけてたのでコミットしただけで行けると思ってました。
再起動して確認しました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
修正お疲れさまでした！！

**Comment by TI0946** [comment]
ありがとうございます！
